# Generated by Django 6.0 on 2025-12-10 21:43

import django.db.models.deletion
import fiordispino.core.validators
import fiordispino.models.game
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(validators=[fiordispino.core.validators.validate_genre])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_art', models.ImageField(upload_to=fiordispino.models.game.build_path)),
                ('description', models.TextField(validators=[fiordispino.core.validators.validate_game_description])),
                ('title', models.TextField(validators=[fiordispino.core.validators.validate_title])),
                ('pegi', models.IntegerField(validators=[fiordispino.core.validators.validate_pegi])),
                ('release_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(related_name='games', to='fiordispino.genre')),
            ],
        ),
        migrations.CreateModel(
            name='GamesToPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='played_by_users', to='fiordispino.game')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_to_play', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game to play',
                'verbose_name_plural': 'Games to play',
                'unique_together': {('owner', 'game')},
            },
        ),
    ]
