# Generated by Django 6.0 on 2025-12-14 18:19

import django.db.models.deletion
import django.utils.timezone
import fiordispino.core.validators
import fiordispino.models.game
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(validators=[fiordispino.core.validators.validate_genre])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_art', models.ImageField(upload_to=fiordispino.models.game.build_path)),
                ('description', models.TextField(validators=[fiordispino.core.validators.validate_game_description])),
                ('title', models.TextField(validators=[fiordispino.core.validators.validate_title])),
                ('global_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[fiordispino.core.validators.validate_global_rating])),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('pegi', models.IntegerField(validators=[fiordispino.core.validators.validate_pegi])),
                ('release_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(related_name='games', to='fiordispino.genre')),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[fiordispino.core.validators.validate_vote])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='played_by_user', to='fiordispino.game')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='played_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game played',
                'verbose_name_plural': 'Games played',
                'unique_together': {('owner', 'game')},
            },
        ),
        migrations.CreateModel(
            name='GamesToPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_be_played_by_user', to='fiordispino.game')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_to_play', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game to play',
                'verbose_name_plural': 'Games to play',
                'unique_together': {('owner', 'game')},
            },
        ),
    ]
