# Generated by Django 6.0 on 2025-12-14 16:58

import fiordispino.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiordispino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='global_rating',
            field=models.FloatField(default=0.0, validators=[fiordispino.core.validators.validate_global_rating]),
        ),
        migrations.AddField(
            model_name='game',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
