# Generated by Django 5.2.8 on 2025-12-09 15:26

import fiordispino.core.validators
import fiordispino.models.game
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiordispino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_art', models.ImageField(upload_to=fiordispino.models.game.build_path)),
                ('description', models.TextField(validators=[fiordispino.core.validators.validate_game_description])),
                ('title', models.TextField(validators=[fiordispino.core.validators.validate_title])),
                ('pegi', models.IntegerField(validators=[fiordispino.core.validators.validate_pegi])),
                ('release_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(related_name='games', to='fiordispino.genre')),
            ],
        ),
    ]
