# Generated by Django 6.0 on 2025-12-14 17:42

import fiordispino.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiordispino', '0002_game_global_rating_game_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='global_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[fiordispino.core.validators.validate_global_rating]),
        ),
    ]
