# Generated by Django 5.2.8 on 2025-12-10 11:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiordispino', '0003_gamestoplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestoplay',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamestoplay',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
